name: Use Secrets in Workflow

on: workflow_dispatch

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print a Secret
      env:
        test_secret: ${{secrets.test_secret}}
      run: |
        echo "The secret text is: $test_secret"
